name: "RFC Validation: Stub"
description: "Stub: Don't use this action directly."
branding:
  icon: "check-circle"
  color: "green"
runs:
  using: "composite"
  steps:
    - name: Stub
      shell: bash
      run: |
        echo "This is a stub"
        exit 1
